### ISSUE TITLE
Show image only once it has finished downloading.

### ISSUE THREAD

**Issue by hankijord** [hankijord/tabletalk#2]
Visualisation currently attempts to show image even though it has not finished downloading.
Implement a callback once the image download has finished to display image.

**Comment by rraihansaputra** [comment]
Bug fixed in commit https://github.com/hankijord/tabletalk/commit/518cd1eecfe97a020720c2c2a728924053eb42c7. Now search.py does not download the images themselves, but only fetches the URL to be appended in a text file. The download and display of the image is handled by kivy using asyncImages so the image will only displayed after it has finished downloading. I think this is better than implementing a callback once the image download has finished to maintain separation between audio.py and the visualisation files.
